version: "3.4"

services:
    proxy:
        container_name: proxy
        image: proxy
        restart: always
        build:
            context: .
            dockerfile: ./docker/proxy.Dockerfile
            target: proxy
        ports:
            - 80:80
        depends_on: 
            - backend
            - web

    web:
        container_name: web
        image: web
        restart: always
        build:
            context: .
            dockerfile: ./docker/web.Dockerfile
            target: web
        env_file:
            - .env
        ports:
            - $WEBDROP_WEB_PORT:3000

    backend:
        container_name: backend
        image: backend
        restart: always
        build:
            context: .
            dockerfile: ./docker/backend.Dockerfile
            target: backend
        env_file:
            - .env
        ports:
            - $WEBDROP_BACKEND_PORT:4000
