name: CI
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: # Ideally this will be stored in github secrets and will be accessed via ${{ secrets.* }}
      NODE_ENV: production
      WEBDROP_WEB_PORT: 3000
      WEBDROP_WEB_ENDPOINT: http://localhost:3000
      WEBDROP_BACKEND_PORT: 4000
      WEBDROP_BACKEND_ENDPOINT: http://localhost:4000

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Prepare build
      run: touch .env

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.WEBDROP_ECR_REPOSITORY }}
      run: |
        echo $ECR_REGISTRY
        echo $ECR_REPOSITORY
        # Build images
        docker-compose build
        echo Images built
        docker images
        # Tag images
        IMAGE_TAG=${GITHUB_SHA:0:7}
        echo Tag $IMAGE_TAG
        docker tag web:latest 332333453971.dkr.ecr.us-east-1.amazonaws.com/webdrop:web-$IMAGE_TAG
        docker tag backend:latest 332333453971.dkr.ecr.us-east-1.amazonaws.com/webdrop:backend-$IMAGE_TAG
        docker images
        # Push images to ECR
        docker push 332333453971.dkr.ecr.us-east-1.amazonaws.com/webdrop:web-$IMAGE_TAG
        echo Pushed webdrop/web to ECR
        docker push 332333453971.dkr.ecr.us-east-1.amazonaws.com/webdrop:backend-$IMAGE_TAG
        echo Pushed webdrop/backend to ECR